# Generated by Django 4.2.30 on 2026-09-08 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'actividades',
                'db_table': 'actividad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Arl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ARL',
                'verbose_name_plural': 'ARL',
                'db_table': 'arl',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('genera_viaticos', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'ciudades',
                'db_table': 'ciudad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=40)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('arl', models.ForeignKey(db_column='arl_id', on_delete=django.db.models.deletion.PROTECT, to='ordenes.arl')),
            ],
            options={
                'db_table': 'contrato',
                'ordering': ['numero_contrato'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'empresa cliente',
                'verbose_name_plural': 'empresas cliente',
                'db_table': 'empresa_cliente',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('orden_flujo', models.SmallIntegerField()),
                ('es_inicial', models.BooleanField(default=False)),
                ('es_final', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'estado de la orden',
                'verbose_name_plural': 'estados de la orden',
                'db_table': 'estado_orden',
                'ordering': ['orden_flujo'],
            },
        ),
        migrations.CreateModel(
            name='ProfesionalHiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'profesional de HISO',
                'verbose_name_plural': 'profesionales de HISO',
                'db_table': 'profesional_hiso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RpaStgOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arl_codigo', models.CharField(default='COLMENA', max_length=20)),
                ('num_orden', models.TextField(blank=True, null=True)),
                ('responsable_colmena', models.TextField(blank=True, null=True)),
                ('num_contrato', models.TextField(blank=True, null=True)),
                ('nit_orden', models.TextField(blank=True, null=True)),
                ('empresa', models.TextField(blank=True, null=True)),
                ('actividad', models.TextField(blank=True, null=True)),
                ('cantidad_solicitada', models.TextField(blank=True, null=True)),
                ('lugar_realizacion', models.TextField(blank=True, null=True)),
                ('contacto_actividad', models.TextField(blank=True, null=True)),
                ('ciudad_desarrollo', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.TextField(blank=True, null=True)),
                ('fecha_fin', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('valor_total', models.TextField(blank=True, null=True)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'orden en bandeja del robot',
                'verbose_name_plural': 'bandeja del robot',
                'db_table': 'rpa_stg_orden',
                'ordering': ['-recibido_en'],
            },
        ),
        migrations.CreateModel(
            name='RpaEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('ordenes_detectadas', models.IntegerField(default=0)),
                ('ordenes_cargadas', models.IntegerField(default=0)),
                ('resultado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('OK', 'Correcta'), ('SIN_DATOS', 'Sin órdenes nuevas'), ('ERROR', 'Con error')], default='EN_CURSO', max_length=20)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('arl', models.ForeignKey(db_column='arl_id', on_delete=django.db.models.deletion.PROTECT, to='ordenes.arl')),
            ],
            options={
                'verbose_name': 'ejecución del robot',
                'verbose_name_plural': 'ejecuciones del robot',
                'db_table': 'rpa_ejecucion',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='ResponsableArl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=200, null=True)),
                ('arl', models.ForeignKey(db_column='arl_id', on_delete=django.db.models.deletion.PROTECT, to='ordenes.arl')),
            ],
            options={
                'verbose_name': 'responsable de la ARL',
                'verbose_name_plural': 'responsables de la ARL',
                'db_table': 'responsable_arl',
                'ordering': ['nombre'],
                'unique_together': {('arl', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=30)),
                ('cantidad_solicitada', models.IntegerField(blank=True, null=True)),
                ('lugar_realizacion', models.TextField(blank=True, null=True)),
                ('contacto_actividad', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('origen_captura', models.CharField(choices=[('RPA', 'Captura automática'), ('MANUAL', 'Registro manual')], default='RPA', max_length=10)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(db_column='actividad_id', on_delete=django.db.models.deletion.PROTECT, to='ordenes.actividad')),
                ('arl', models.ForeignKey(db_column='arl_id', on_delete=django.db.models.deletion.PROTECT, to='ordenes.arl')),
                ('ciudad', models.ForeignKey(db_column='ciudad_id', on_delete=django.db.models.deletion.PROTECT, to='ordenes.ciudad')),
                ('contrato', models.ForeignKey(blank=True, db_column='contrato_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.contrato')),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.PROTECT, to='ordenes.estadoorden')),
                ('profesional_hiso', models.ForeignKey(blank=True, db_column='profesional_hiso_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.profesionalhiso')),
                ('responsable_arl', models.ForeignKey(blank=True, db_column='responsable_arl_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.responsablearl')),
            ],
            options={
                'verbose_name': 'orden de servicio',
                'verbose_name_plural': 'órdenes de servicio',
                'db_table': 'orden_servicio',
                'ordering': ['-fecha_captura'],
                'unique_together': {('arl', 'numero_orden')},
            },
        ),
        migrations.CreateModel(
            name='OrdenHistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(default='RPA', max_length=120)),
                ('nota', models.TextField(blank=True, null=True)),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.PROTECT, to='ordenes.estadoorden')),
                ('orden_servicio', models.ForeignKey(db_column='orden_servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ordenes.ordenservicio')),
            ],
            options={
                'verbose_name': 'cambio de estado',
                'verbose_name_plural': 'historial de estados',
                'db_table': 'orden_historial_estado',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='OrdenDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='FORMATO_PRESTACION', max_length=40)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta', models.TextField()),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('orden_servicio', models.ForeignKey(db_column='orden_servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ordenes.ordenservicio')),
            ],
            options={
                'verbose_name': 'documento de la orden',
                'verbose_name_plural': 'documentos de la orden',
                'db_table': 'orden_documento',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa_cliente',
            field=models.ForeignKey(db_column='empresa_cliente_id', on_delete=django.db.models.deletion.PROTECT, to='ordenes.empresacliente'),
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('arl', 'numero_contrato')},
        ),
    ]
